server:
  port: 8082
  servlet:
    context-path: /sxiao
index-html: cmd /c start http://localhost:8082/sxiao/main/index           #index 界面  用来测试获取值
loginuser:
  name: sxiao
  pwd: 1hbl3qt.
spring:
  datasource:
    url: jdbc:mysql://111.229.178.45:3306/mysql
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
